version: '3.8'

services:
  server:
    image: luminainc/server:1.20.1
    platform: linux/arm64
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - REDIS_HOST=redis
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      - postgres
      - redis
      - minio

  web:
    image: luminainc/web:1.20.1
    platform: linux/arm64
    ports:
      - "5173:8000"
    environment:
      - API_URL=http://localhost:8000/api
    depends_on:
      - server

  postgres:
    image: postgres:14
    platform: linux/arm64
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    platform: linux/arm64
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    platform: linux/arm64
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  adminer:
    image: adminer:latest
    platform: linux/arm64
    ports:
      - "8082:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  minio_data: 