// Mock data for testing deal flow UI without backend
// TODO: Remove this file once backend is fully operational

import { DealResponse, DocumentResponse, FactResponse } from "./dealApi";

export const MOCK_DEALS: DealResponse[] = [
  {
    deal_id: "deal-001-mockdata",
    user_id: "mock-user-001",
    deal_name: "Main Street Apartments",
    status: "draft",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    metadata: {},
    document_count: 0,
    fact_count: 0,
  },
  {
    deal_id: "deal-002-mockdata",
    user_id: "mock-user-001",
    deal_name: "Downtown Commercial Property",
    status: "processing_documents",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    metadata: {},
    document_count: 2,
    fact_count: 3,
  },
  {
    deal_id: "deal-003-mockdata",
    user_id: "mock-user-001",
    deal_name: "Riverside Townhomes",
    status: "ready_for_underwriting",
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    metadata: {},
    document_count: 4,
    fact_count: 7,
  },
];

export const MOCK_DOCUMENTS: DocumentResponse[] = [
  {
    document_id: "doc-001-mockdata",
    deal_id: "deal-003-mockdata",
    file_name: "Rent_Roll_2024.pdf",
    document_type: "rent_roll",
    status: "processed",
    storage_location: "/mock-documents/Rent_Roll_2024.pdf",
    page_count: 3,
    created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    fact_count: 3,
  },
  {
    document_id: "doc-002-mockdata",
    deal_id: "deal-003-mockdata",
    file_name: "T12_Profit_Loss.pdf",
    document_type: "profit_and_loss",
    status: "processed",
    storage_location: "/mock-documents/T12_Profit_Loss.pdf",
    page_count: 5,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    fact_count: 2,
  },
  {
    document_id: "doc-003-mockdata",
    deal_id: "deal-003-mockdata",
    file_name: "Mortgage_Statement_Jan2024.pdf",
    document_type: "mortgage_statement",
    status: "processed",
    storage_location: "/mock-documents/Mortgage_Statement_Jan2024.pdf",
    page_count: 2,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    fact_count: 1,
  },
  {
    document_id: "doc-004-mockdata",
    deal_id: "deal-003-mockdata",
    file_name: "Property_Tax_2023.pdf",
    document_type: "tax_document",
    status: "pending",
    storage_location: "/mock-documents/Property_Tax_2023.pdf",
    page_count: 1,
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    fact_count: 1,
  },
];

export const MOCK_FACTS: FactResponse[] = [
  {
    fact_id: "fact-001-mockdata",
    document_id: "doc-001-mockdata",
    deal_id: "deal-003-mockdata",
    fact_type: "financial",
    label: "Unit Count",
    value: "24",
    unit: undefined,
    source_citation: {
      document: "Rent_Roll_2024.pdf",
      page: 1,
      line: "Total Units: 24",
    },
    status: "pending_approval",
    confidence_score: 0.95,
    approved_at: undefined,
    approved_by: undefined,
    locked: false,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    fact_id: "fact-002-mockdata",
    document_id: "doc-001-mockdata",
    deal_id: "deal-003-mockdata",
    fact_type: "financial",
    label: "Occupancy %",
    value: "87.5",
    unit: "%",
    source_citation: {
      document: "Rent_Roll_2024.pdf",
      page: 1,
      line: "Current Occupancy: 87.5%",
    },
    status: "pending_approval",
    confidence_score: 0.92,
    approved_at: undefined,
    approved_by: undefined,
    locked: false,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    fact_id: "fact-003-mockdata",
    document_id: "doc-001-mockdata",
    deal_id: "deal-003-mockdata",
    fact_type: "financial",
    label: "Gross Scheduled Rent",
    value: "432000",
    unit: "USD/year",
    source_citation: {
      document: "Rent_Roll_2024.pdf",
      page: 2,
      line: "Annual Gross Rent: $432,000",
    },
    status: "pending_approval",
    confidence_score: 0.98,
    approved_at: undefined,
    approved_by: undefined,
    locked: false,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    fact_id: "fact-004-mockdata",
    document_id: "doc-002-mockdata",
    deal_id: "deal-003-mockdata",
    fact_type: "financial",
    label: "Collected Rent",
    value: "378000",
    unit: "USD/year",
    source_citation: {
      document: "T12_Profit_Loss.pdf",
      page: 1,
      line: "Actual Collections (T-12): $378,000",
    },
    status: "pending_approval",
    confidence_score: 0.96,
    approved_at: undefined,
    approved_by: undefined,
    locked: false,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    fact_id: "fact-005-mockdata",
    document_id: "doc-002-mockdata",
    deal_id: "deal-003-mockdata",
    fact_type: "financial",
    label: "Operating Expenses",
    value: "145000",
    unit: "USD/year",
    source_citation: {
      document: "T12_Profit_Loss.pdf",
      page: 3,
      line: "Total Operating Expenses: $145,000",
    },
    status: "pending_approval",
    confidence_score: 0.88,
    approved_at: undefined,
    approved_by: undefined,
    locked: false,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    fact_id: "fact-006-mockdata",
    document_id: "doc-003-mockdata",
    deal_id: "deal-003-mockdata",
    fact_type: "debt",
    label: "Debt Service",
    value: "180000",
    unit: "USD/year",
    source_citation: {
      document: "Mortgage_Statement_Jan2024.pdf",
      page: 1,
      line: "Annual Debt Service: $180,000",
    },
    status: "pending_approval",
    confidence_score: 0.94,
    approved_at: undefined,
    approved_by: undefined,
    locked: false,
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    fact_id: "fact-007-mockdata",
    document_id: "doc-004-mockdata",
    deal_id: "deal-003-mockdata",
    fact_type: "tax",
    label: "Property Value",
    value: "3500000",
    unit: "USD",
    source_citation: {
      document: "Property_Tax_2023.pdf",
      page: 1,
      line: "Assessed Value: $3,500,000",
    },
    status: "pending_approval",
    confidence_score: 0.85,
    approved_at: undefined,
    approved_by: undefined,
    locked: false,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const isMockDeal = (dealId?: string): boolean => {
  return dealId ? dealId.includes("mockdata") : false;
};

export const generateMockDealId = (): string => {
  return `deal-${Date.now()}-mockdata`;
};

export const createMockDeal = (dealName: string): DealResponse => {
  return {
    deal_id: generateMockDealId(),
    user_id: "mock-user-001",
    deal_name: dealName,
    status: "draft",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    metadata: {},
    document_count: 0,
    fact_count: 0,
  };
};

