apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: data-extract
type: Opaque
data:
  host: <base64-encoded-host>
  username: <base64-encoded-username>
  password: <base64-encoded-password>
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: data-extract
type: Opaque
data:
  access-key: <base64-encoded-access-key>
  secret-key: <base64-encoded-secret-key> 