apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: orin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: server
        image: ghcr.io/buildorin/orin-server:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: host
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: REDIS_HOST
          value: redis
        - name: MINIO_ENDPOINT
          value: minio:9000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: orin
spec:
  selector:
    app: server
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP 